apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql8:3306"
  database: "msvc_usuarios"
  #  username: "root"
  #  password: "angel2389"
  curso_url: "msvc-cursos:8002"
  application.yaml: |-
    config:
      texto: "Configurando ambiente por defect o"
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: "Configurando ambiente de desarrollo"
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: "Configurando ambiente de producción"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres15:5432"
  database: "msvc_cursos"
  #  username: "postgres"
  #  password: "gabo12345"
  usuario_url: "msvc-usuarios:8001"

