services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: angel2389
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - spring
  postgres15:
    container_name: postgres15
    image: postgres:15-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: gabo12345
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    image: angelx23/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
  msvc-cursos:
    container_name: msvc-cursos
    image: angelx23/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres15
      - msvc-usuarios
    restart: always
volumes:
  data-mysql:
    external: true
  data-postgres:
    external: true
networks:
  spring:
    external: true


